#Message
#The & symbol replaces the ยง symbol for color coding! 
#Use {LINE} to go down to the next line!
#Use {KILLS} to show the players Kills! (REQUIRES PLAYERSTATS BY IMAGICALGAMER)
#Use {DEATHS} to show the players deaths! (REQUIRES PLAYERSTATS BY IMAGICALGAMER)
#Use {MONEY} to show the players money! (REQUIRES ECONOMYAPI BY ONEBONE)
#Use {MAXONLINE} to show how much the server slots is!
#Use {ONLINE} to show how much people on the server!
Message: '&b&lWelcome to &cMy Server! Kills: {KILLS} Money: {MONEY} Online:{ONLINE} / {MAXONLINE}'
Enable-Money: true
Enable-Stats: true
